#!/bin/sh

# va stands for "vocab add"

# run vocab add, if it fails store an empty string instead
# (jank ass motherfucker alert)
term="$(./vocab add $@ || echo '')"

# only call vim if term is non-empty string, which means that ./vocab add did not fail
if [ -n "$term" ]; then
	vim "$term"
fi
